version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:
  
services:
  db:
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  backend:
    image: alexeyastapoff/foodgram_backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - data_value:/app/data/
    env_file: .env
    depends_on:
      - db
   

  frontend:
    image: alexeyastapoff/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - data_value:/var/html/data/

    depends_on:
      - backend
      - frontend