# users models

MAX_LENGTH_EMAIL_FIELD = 254
MAX_LENGTH_CHAR_FIELD = 150
USERNAME = 'email'

# rcipes models

MAX_LENGTH_CHAR_FIELD = 200
MAX_LENGTH_COLOR = 7
MAX_VALUE_TIME = 1440
MIN_VALUE_TIME = 1
MAX_VALUE_AMOUNT = 20
MIN_VALUE_AMOUNT = 1
